# Site settings
title: raulperula
email:
url: http://raulperula.github.io
phone: +34
description: ""
owner-name: Raúl
owner-surname: Pérula-Martínez
owner-role: Artificial Intelligence Researcher
aboutA: ""
aboutB: ""
blog: ""
keywords: [robotics, artificial intelligence, generative ai, nlp, computer vision, cv]

cv-image: /img/profile_photo.jpg

# Social networks
social:
  - title: github
    url: https://github.com/raulperula
  - title: linkedin
    url: http://www.linkedin.com/in/raulperula
  - title: twitter
    url: https://twitter.com/raulperula

# Postal address (add as many lines as necessary)
address:
  - line: Spain

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap

# Some more default colors (hex-codes without the leading hash-tag)
color:
  articletext: 4e4e4e # This is the text color
  primary: c4e59c # This is the gray color with a green tint
  secondary: 84ad52 # This is the green color
  secondary-dark: 6e9145 # This is the dark green color
  secondary-alpha: rgba(132,173,82,.7) # This is the same as the secondary color but with an alpha value
  tertiary: 7a3bff # This is purple
